name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Go to front-end folder
        run: cd front-end/
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Move back to main folder
        run: cd ../
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: front-end/out
          path: front-end/out
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: front-end/out
          path: front-end/out
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@main
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
