name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      functions: ${{ steps.filter.outputs.functions }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'front-end/**'
            functions:
              - 'functions/**'

  build_frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        working-directory: ./front-end
        run: yarn install
      - name: Build Next.js
        working-directory: ./front-end
        run: yarn run build
      - name: Export Next.js bundle
        working-directory: ./front-end
        run: yarn run export
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: frontend
          path: front-end/out

  deploy:
    name: Deploy
    needs: build_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: frontend
          path: front-end/out
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
