name: Deploy Front End Preview on PR

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    paths:
      - "front-end/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./front-end
        run: yarn install
      - name: Build Next.js
        working-directory: ./front-end
        run: yarn run build
      - name: Export Next.js bundle
        working-directory: ./front-end
        run: yarn run export
      - name: Archive Preview Artifact
        uses: actions/upload-artifact@v2
        with:
          name: distOfPR
          path: front-end/out
  deploy:
    name: Deploy Preview
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: distOfPR
          path: front-end/out
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: preview_step
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: your-Firebase-project-ID
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Echo URL
        run: |
          echo "${{ steps.preview_step.outputs.details_url }}\n"
          echo "${{ steps.preview_step.outputs.urls }}\n"
          echo "${{ steps.preview_step.outputs.expire_time }}\n"
